# Generated by Django 4.0.2 on 2022-02-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sites_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='status',
            new_name='is_scam',
        ),
    ]
